spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/my_finance_map?createDatabaseIfNotExist=true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  mvc:
    format:
      date-time: iso

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: myfinancemap@gmail.com
    password: yzresohpszotyjdl
    port: '587'


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-myfinancemap.html

server:
  port: 8080