spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/my_finance_map?createDatabaseIfNotExist=true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  mvc:
    format:
      date-time: iso
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-myfinancemap.html

server:
  port: 8080